# Generated by Django 5.2.17 on 2026-08-27 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('RETURN', 'Return'), ('CORRECTION', 'Correction'), ('STOCK_ADJUSTMENT', 'Stock adjustment'), ('DAMAGE', 'Damage')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reason', models.TextField()),
                ('requested_changes', models.JSONField(blank=True, default=dict)),
                ('reviewer_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='accounts.branch')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='sales.sale')),
                ('stock_count', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='inventory.stockcount')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('client_return_id', models.UUIDField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_return', to='sales.approvalrequest')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='accounts.branch')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank transfer'), ('POS', 'POS / card')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_issued', to=settings.AUTH_USER_MODEL)),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.salereturn')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('RESELLABLE', 'Resellable — restored to inventory'), ('DAMAGED_OR_OPENED', 'Damaged or opened — not restored')], max_length=20)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('original_sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salereturn')),
            ],
            options={
                'ordering': ['original_sale_item__sku_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['branch', 'status', '-created_at'], name='sales_appro_branch__7ec35b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['request_type', 'status'], name='sales_appro_request_40de6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='salereturn',
            constraint=models.UniqueConstraint(fields=('branch', 'client_return_id'), name='salereturn_unique_branch_client_id'),
        ),
        migrations.AddConstraint(
            model_name='salereturn',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='salereturn_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='salereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='salereturnitem_qty_gt_0'),
        ),
    ]
