# Generated by Django 5.2.17 on 2026-08-27 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_offlinedeviceauthorization'),
        ('sales', '0002_approvalrequest_salereturn_refund_salereturnitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='offline_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OfflineSaleSyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_sale_id', models.UUIDField()),
                ('device_sequence', models.PositiveIntegerField()),
                ('offline_created_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'Accepted — official Sale created'), ('DUPLICATE', 'Duplicate — already synced'), ('CONFLICT', 'Conflict — retained for owner resolution'), ('REJECTED', 'Rejected — invalid payload'), ('OWNER_REVIEW_REQUIRED', 'Owner review required')], max_length=24)),
                ('detail_code', models.CharField(blank=True, max_length=60)),
                ('redacted_payload', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_records', to='accounts.offlinedeviceauthorization')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_sync_records', to='accounts.branch')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_sync_records', to='accounts.registereddevice')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sync_records_resolved', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offline_sync_record', to='sales.sale')),
            ],
            options={
                'ordering': ['device_sequence', 'created_at'],
                'indexes': [models.Index(fields=['branch', 'outcome'], name='sales_offli_branch__f463e5_idx'), models.Index(fields=['authorization', 'device_sequence'], name='sales_offli_authori_3b1e9f_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'client_sale_id'), name='offlinesyncrecord_unique_branch_client_id')],
            },
        ),
    ]
