# Generated by Django 5.2.17 on 2026-08-31 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_offlinedeviceauthorization'),
        ('catalog', '0001_initial'),
        ('sales', '0003_payment_offline_confirmed_offlinesalesyncrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSaleReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('RECORDED_AS_SALE', 'Recorded as an official sale'), ('REFUNDED_AND_RETURNED', 'Refunded — all goods returned, no sale'), ('LINKED_EXISTING_SALE', 'Linked to an owner-entered official sale')], max_length=24)),
                ('resolved_at', models.DateTimeField()),
                ('explanation', models.TextField()),
                ('receipt_number', models.CharField(blank=True, max_length=40)),
                ('linked_manually', models.BooleanField(default=False)),
                ('refund_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_source', models.CharField(blank=True, choices=[('SNAPSHOT_VERIFIED', 'Sale total recomputed from the cryptographically verified frozen snapshot'), ('RETAINED_PAYMENTS_MATCHED_TO_SNAPSHOT', 'Retained device payments parsed cleanly and equal the verified snapshot total'), ('OWNER_ATTESTED', 'Owner-attested amount collected (retained data could not establish it)')], max_length=40)),
                ('link_verification', models.CharField(blank=True, choices=[('FULL', 'All three dimensions were comparable and every one matched'), ('PARTIAL', 'Every comparable dimension matched; fewer than three could be compared'), ('MANUAL_ATTESTED', 'No dimension was comparable — owner-attested manual match')], max_length=16)),
                ('verified_snapshot_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('retained_payments_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('completion_time_substituted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_reconciliations', to='accounts.branch')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offline_reconciliation', to='sales.sale')),
                ('sync_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='sales.offlinesalesyncrecord')),
            ],
            options={
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineReconciliationRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank transfer'), ('POS', 'POS / card')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.offlinesalereconciliation')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='offlinereconrefund_amount_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='OfflineReconciliationCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counted_on_hand', models.PositiveIntegerField()),
                ('quantity_in_offline_sale', models.PositiveIntegerField()),
                ('db_quantity_before', models.IntegerField()),
                ('correction_delta', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='sales.offlinesalereconciliation')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('reconciliation', 'variant'), name='offlinereconcount_unique_variant')],
            },
        ),
    ]
