# Generated by Django 5.2.17 on 2026-08-27 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineDeviceAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('signed_token', models.TextField()),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active — offline session running'), ('CLOSED', 'Closed — session ended, all sales synced'), ('FORCE_CLOSED', 'Force-closed by owner with pending sales'), ('REVOKED', 'Revoked'), ('REPLACED', 'Replaced by a newer authorization')], default='ACTIVE', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=300)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_authorizations_granted', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_authorizations', to='accounts.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_authorizations_as_cashier', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_authorizations', to='accounts.registereddevice')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_authorizations_ended', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'status'], name='accounts_of_branch__f17ae5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('branch',), name='one_active_offline_authorization_per_branch'), models.UniqueConstraint(fields=('branch', 'snapshot_version'), name='offlineauth_unique_branch_version')],
            },
        ),
    ]
