# Generated by Django 5.2.17 on 2026-08-27 13:02

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='accounts.branch')),
            ],
            options={
                'verbose_name_plural': 'expense categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expense_date', models.DateField()),
                ('description', models.TextField()),
                ('receipt_file', models.FileField(blank=True, upload_to='expenses/%Y/%m/')),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounts.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_voided', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(models.F('branch'), django.db.models.functions.text.Lower('name'), name='expensecategory_branch_name_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch', 'expense_date'], name='finance_exp_branch__a767bb_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch', 'is_voided'], name='finance_exp_branch__df7476_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_gt_0'),
        ),
    ]
