# Generated by Django 5.2.17 on 2026-08-27 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('reason', models.TextField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts_applied', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='accounts.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='accounts.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_file', models.FileField(blank=True, upload_to='restocks/%Y/%m/')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restocks', to='accounts.branch')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restocks_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restocks_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restocks', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('average_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='accounts.branch')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['variant__sku'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'variant'), name='inventorybalance_unique_branch_variant'), models.CheckConstraint(condition=models.Q(('average_unit_cost__gte', 0)), name='inventorybalance_avg_cost_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='RestockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('restock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.restock')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['variant__sku'],
                'constraints': [models.UniqueConstraint(fields=('restock', 'variant'), name='restockitem_unique_variant'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='restockitem_qty_gt_0'), models.CheckConstraint(condition=models.Q(('unit_cost__gt', 0)), name='restockitem_unit_cost_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_quantity_snapshot', models.PositiveIntegerField()),
                ('counted_quantity', models.PositiveIntegerField()),
                ('variance', models.IntegerField(default=0)),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['variant__sku'],
                'constraints': [models.UniqueConstraint(fields=('stock_count', 'variant'), name='stockcountitem_unique_variant')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening stock'), ('RESTOCK', 'Restock'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('DAMAGE', 'Damage / write-off'), ('ADJUSTMENT', 'Correction')], max_length=12)),
                ('quantity_delta', models.IntegerField()),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='accounts.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'variant', '-created_at'], name='inventory_s_branch__9c72ef_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='stockmovement_delta_nonzero')],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['branch', 'is_active'], name='inventory_s_branch__061fcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='restock',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='restock_total_cost_gte_0'),
        ),
    ]
