# Generated by Django 5.2.17 on 2026-08-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING', 'Opening stock'), ('RESTOCK', 'Restock'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('DAMAGE', 'Damage / write-off'), ('ADJUSTMENT', 'Correction'), ('OFFLINE_RECONCILIATION', 'Offline reconciliation')], max_length=24),
        ),
    ]
